### ISSUE TITLE
About pull requests point to `stable`

### ISSUE THREAD

**Issue by cphyc** [ramses-organisation/ramses#19]
I've noticed plenty of pull requests have been made directly onto `stable` (e.g. #17 or #18). While this is great, it would be more beneficial to have the pull requests merged into `dev` instead and *then* backported to `stable` (which can be easily done by labelling the PR with the label `on-merge: backport to stable`. That way, the fixes end up in both rather than solely on `stable`.

**Comment by tinecolman** [comment]
I indeed wasn't sure to which branch to do it. Since I saw things were being put into stable directly at the moment, I just went with that. I've been a bit out of the loop the last few months so I wasn't sure if we already decided on a procedure to follow for bugfixes.

**Comment by rteyssier** [comment]
Good idea! Anyone can do that or is it only the PR owner?

**Comment by cphyc** [comment]
Anyone with triage access can do it (Benoit, Jérémy, Maxime, Tine, you and I).

**Comment by nbrucy** [comment]
Related to that, it appears that `dev` is 40 commit behind `stable`. I'm not sure this is want we want.

**Comment by tinecolman** [comment]
Would it be possible to prevent PRs from forks to the stable branch with some setting or so?

**Comment by rteyssier** [comment]
I guess this is the responsibility of the developers to develop using the dev branch and not the stable branch…

**Comment by nbrucy** [comment]
I think admins can edit the PR (button top right) and change the destination branch.

**Comment by cphyc** [comment]
@rteyssier I agree, but we should *not* merge bugfixes onto stable, but rather backport them. Otherwise, we will end up with a bugfixed master branch, and a bugful dev branch.

As mentioned during the RUM, we can automate most of the work by
1. Always merging onto `dev`,
2. Flag the pull PRs that need to be backported with the label `on-merge: backport to stable`[^1]
3. This will create automatically a PR that backports the fix onto stable, which we can merge.

[^1]: @rteyssier configured the bot following this link https://github.com/apps/lumberbot-app/, see comment below to check it works (if the bot answers, it works!)

**Comment by cphyc** [comment]
@MeeseeksDev Hello

**Comment by cphyc** [comment]
I've ported all PRs from stable to dev, so we can happily merge *only* onto dev from now on!
